spring.application.name=urlShortner
spring.data.mongodb.uri=mongodb+srv://dhavileswarapusaikumar_db_user:hzvly010BJtaZjbT@cluster0.vbj2nyn.mongodb.net/url_shortener?retryWrites=true&w=majority&appName=Cluster0
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [traceID:%X{traceId}] [spanID:%X{spanId}]--- [%thread] %logger{36} : %msg%n
spring.data.mongodb.auto-index-creation=true